### ISSUE TITLE
Hangs on ConformU

### ISSUE THREAD

**Issue by RReverser** [jsorrell/star-adventurer-alpaca#3]
With the latest ConformU, conformance tests against this project hang at the stage of moving axis at maximum rate.

Moving axis at minimum rate executes successfully, but at the maximum rate it successfully starts slewing but then never stops and my Star Adventurer just keeps rotating indefinitely, while ConformU eventually gives up with a timeout error.

**Comment by jsorrell** [comment]
There are a fair few bugs in this project. For example, the time format is incorrect, move motor sometimes doesn't work, and sometimes it will slew in the wrong direction if mount limits are set. However, most functions such as slewing, tracking, and guiding work reliably (for my specific usages). I've mostly rewritten this project from the ground up since (I'll push it publicly once it is stable).

For this specific issue, the problem is that the max speed of the motor is too slow for the conformance tool. It tries to do a big move, but the motor moves too slow so it times out. You have to increase the timeout of the conformance tool to get it to work. I increased the Long Response timeout to 600 and it works.

**Comment by RReverser** [comment]
Ah thanks, I'll try that!

It might be helpful to put instructions in the readme or, better yet, an exported ConformU settings file in the repo for easily reproducible tests.

**Comment by RReverser** [comment]
> I've mostly rewritten this project from the ground up since (I'll push it publicly once it is stable).

FWIW I actually built an Alpaca library for Rust that takes care of both client and server side so you only need to implement traits and it does the rest for you. The reason I came across this project was that I didn't have good ideas for a simple demo for the server side part of it and this seemed like a good match for testing that covers a lot of ground.

I rewritten it to use my Alpaca bindings in a private repo, confirmed it still works with my bindings, and might publish it separately or make a PR if it's something you'd be interested in.
